### ISSUE TITLE
schema-cannot-register-item-twice: A single item cannot be registered twice in the schema. 

### ISSUE THREAD

**Issue by wmhfly** [akilli/ck5#1]
installed show error:

I'm app has two ckeditor!

![image](https://user-images.githubusercontent.com/2811753/64526767-baf7af80-d336-11e9-85d1-0c0928c30b03.png)

**Comment by akilli** [comment]
Do you use the @ckeditor/ckeditor5-media-embed package as well?

**Comment by wmhfly** [comment]
> @ckeditor/ckeditor5-media-embed

Thank you very much for your reply!

Yes, I also found their conflict!
Now I remove @CKEditor/ckeditor5-media embedding, but still report an error:

Hint: toolbarview-item-unavailable: The requested toolbar item is not available

![image](https://user-images.githubusercontent.com/2811753/64529533-b256a780-d33d-11e9-87dd-28b3187d7b65.png)


![image](https://user-images.githubusercontent.com/2811753/64529585-d9ad7480-d33d-11e9-823a-e67692fa0748.png)

**Comment by akilli** [comment]
The media plugin does not define a toolbar item called _media_, but _mediaBrowser_ (see [demo config](https://github.com/akilli/ck5/blob/master/media/dev/config.js#L81)

**Comment by akilli** [comment]
> Yes, I also found their conflict!

The media-embed plugin was released after this one, so there was no schema conflict before. 

But I already had and still have plans to split the different media types and register different elements and toolbar items per type once I've got some free time. Then you could just pick the features you want and use other plugins like image, media-embed, etc for the rest.  As a positive side effect, this would automatically solve the schema conflict too. Therefore I am closing this issue for now.
